component extends="cfselenium.CFSeleniumTestCase" displayName="EndToEnd-Server-newValidations" {

    public void function beforeTests() {
        browserUrl = "http://localhost/validatethis/tests/selenium/FacadeDemo/";
        super.beforeTests();
        selenium.setTimeout(30000);
        crlf = chr(10);
    }

    public void function testEndToEndServerNewValidations() {
        selenium.open("http://localhost/validatethis/tests/selenium/FacadeDemo/index.cfm?init=true&noJS=true&context=newValidations-server");
        assertEquals("ValidateThis Demo Page", selenium.getTitle());
        selenium.type("UserName", "");
        selenium.type("UserPass", "");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("ValidateThis Demo Page", selenium.getTitle());
        assertEquals("The Email Address is required.#crlf#The Email Address must be a date between 2010-01-01 and 2011-12-31.#crlf#The Email Address must be a date in the future. The date entered must come after 2010-12-31.#crlf#The Email Address must be a date in the past. The date entered must come before 2011-02-01.#crlf#The Email Address was not found in the list: 2011-01-30,2011-01-29.", selenium.getText("error-UserName"));
        assertEquals("The Password is required.#crlf#The Password must be a valid boolean.#crlf#The Password must be a true boolean.#crlf#The Password must be a false boolean.", selenium.getText("error-UserPass"));
        assertEquals("The User Group Name is required.", selenium.getText("error-UserGroupName"));
        selenium.type("UserName", "b");
        selenium.type("Nickname", "abcd");
        selenium.type("UserPass", "c");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Nickname must not contain the values of properties named: UserName,UserPass.#crlf#1 patterns were matched but 3 were required.#crlf#The Nickname must be a valid URL.", selenium.getText("error-Nickname"));
        assertEquals("The Email Address must be a date between 2010-01-01 and 2011-12-31.#crlf#The Email Address must be a date in the future. The date entered must come after 2010-12-31.#crlf#The Email Address must be a date in the past. The date entered must come before 2011-02-01.#crlf#The Email Address was not found in the list: 2011-01-30,2011-01-29.", selenium.getText("error-UserName"));
        selenium.type("UserName", "2010-02-02");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Email Address must be a date in the future. The date entered must come after 2010-12-31.#crlf#The Email Address was not found in the list: 2011-01-30,2011-01-29.", selenium.getText("error-UserName"));
        selenium.type("UserName", "2011-02-02");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Email Address must be a date in the past. The date entered must come before 2011-02-01.#crlf#The Email Address was not found in the list: 2011-01-30,2011-01-29.", selenium.getText("error-UserName"));
        selenium.type("UserName", "2011-01-31");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Email Address was not found in the list: 2011-01-30,2011-01-29.", selenium.getText("error-UserName"));
        selenium.type("UserName", "2011-01-29");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Email Address was found in the list: 2011-01-29,2011-01-28.", selenium.getText("error-UserName"));
        selenium.type("UserName", "2011-01-30");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertFalse(selenium.isElementPresent("error-UserName"));
        selenium.type("UserName", "2011-01-29");
        selenium.type("Nickname", "<a href=2011-01-29>");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Nickname cannot contain HTML tags.#crlf#The Nickname must not contain the values of properties named: UserName,UserPass.#crlf#The Nickname must be a valid URL.", selenium.getText("error-Nickname"));
        selenium.type("Nickname", "2011-01-29");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Nickname must not contain the values of properties named: UserName,UserPass.#crlf#2 patterns were matched but 3 were required.#crlf#The Nickname must be a valid URL.", selenium.getText("error-Nickname"));
        selenium.type("Nickname", "http://www.Abc.com");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertFalse(selenium.isElementPresent("error-Nickname"));
        selenium.type("UserPass", "abc");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Password must be a valid boolean.#crlf#The Password must be a true boolean.#crlf#The Password must be a false boolean.", selenium.getText("error-UserPass"));
        selenium.type("UserPass", "yes");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Password must be a false boolean.", selenium.getText("error-UserPass"));
        selenium.type("UserPass", "0");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Password must be a true boolean.", selenium.getText("error-UserPass"));
        selenium.type("VerifyPassword", "ab");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Verify Password size is not between 3 and 10.", selenium.getText("error-VerifyPassword"));
        selenium.type("VerifyPassword", "abc");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertFalse(selenium.isElementPresent("error-VerifyPassword"));
        selenium.type("VerifyPassword", "a,b");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Verify Password size is not between 3 and 10.", selenium.getText("error-VerifyPassword"));
        selenium.type("VerifyPassword", "a,b,c");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertFalse(selenium.isElementPresent("error-VerifyPassword"));
        selenium.type("VerifyPassword", "structbad");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Verify Password size is not between 3 and 10.", selenium.getText("error-VerifyPassword"));
        selenium.type("VerifyPassword", "structok");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertFalse(selenium.isElementPresent("error-VerifyPassword"));
        selenium.type("VerifyPassword", "arraybad");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertEquals("The Verify Password size is not between 3 and 10.", selenium.getText("error-VerifyPassword"));
        selenium.type("VerifyPassword", "arrayok");
        selenium.click("//button[@type='submit']");
        selenium.waitForPageToLoad("30000");
        assertFalse(selenium.isElementPresent("error-VerifyPassword"));
    }
}
